### PR TITLE
Remove unnecessary vendor

### PR DESCRIPTION
**Pull request by ZloyDyadka**
Vendor in the context of this library is not needed

### CODE REVIEW

**Comment by yl2chen** [comment]
vendor files in in vendor/ and version is managed through glide.

**Comment by ZloyDyadka** [comment]
https://golang.github.io/dep/docs/FAQ.html#a-id-my-dependers-don-t-use-dep-yet-what-should-i-do-a-my-dependers-don-t-use-dep-yet-what-should-i-do

**Comment by ZloyDyadka** [comment]
@yl2chen https://golang.github.io/dep/docs/FAQ.html#a-id-my-dependers-don-t-use-dep-yet-what-should-i-do-a-my-dependers-don-t-use-dep-yet-what-should-i-do

**Comment by yl2chen** [comment]
@ZloyDyadka Sorry for dismissing this prematurely, checking in vendor directory in the glide world is really up to the project owner, and I chose to include as a start for convention for this project, despite testify is only used for testing.  Seems like dep is the official dependency managed for golang, I will migrate to dep thanks.

**Comment by yl2chen** [comment]
https://github.com/yl2chen/cidranger/commit/928b519e5268fe386d0f7decce320205cc09ca95 contains the migration, thanks!

**Pull request closed without merging**
